---
title: "mp2"
author: "Zoya and Khulood"
date: "3/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
install.packages("naniar")
```

```{r}
library(tidyverse)
library(naniar)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
first_jim <- candidates %>%
  filter(cand_id == "H8WA07132")
first_jim
```

```{r}
first_jim <- first_jim %>%
  select(cand_id, cand_name, cand_party_affiliation, cand_office_state) %>%
  inner_join(committees, by = "cand_id")
first_jim
```

```{r}
committees %>%
  group_by(cand_id) %>%
  summarise(n = n_distinct(cmte_name)) %>%
  arrange(desc(n)) %>%
  head(10)
```

```{r}
committees
```


```{r}
first_committee <- committees %>%
  select(cmte_id, cmte_name, cmte_state, cmte_party_affiliation, org_type, cand_id) 
```

```{r}
first_candidate <- candidates %>% 
  select(cand_id, cand_name, cand_party_affiliation, cand_state, cand_office) %>%
  inner_join(first_committee, by = "cand_id")
first_candidate %>%
  filter(cmte_party_affiliation== "DEM")
```

on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

    git config --global user.name "Your Name"
    git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author





